version: '3'

volumes:
  node-modules:
    external: false
  shards:
    external: false
  lib:
    external: false

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      - CRANKY_LOGIN
      - CRANKY_PASSWORD
      - CRANKY_TITLE
    ports:
     - "3000:3000"
    volumes:
      - .:/work:cached
      - lib:/work/lib:delegated
      - shards:/work/.shards:delegated
    tty: true
    command: sh -c '(shards check || shards install) && crystal run support/sentry.cr'

  webpack:
    image: node:9
    working_dir: /work
    volumes:
      - .:/work:cached
      - node-modules:/work/node_modules:delegated
    tty: true
    ports:
     - "8080:8080"
    command: sh -c 'yarn install && yarn run web:devserver'
