version: '2'

tasks:
  build:docker:
    desc: Build the "crankypants-build" image.
    cmds:
      - docker build -t crankypants-build .

  spec:
    desc: Run Crystal specs.
    cmds:
      - crystal spec

  spec:e2e:
    desc: Run E2E tests.
    cmds:
      - docker-compose -f docker-compose.tests.yml up --abort-on-container-exit --exit-code-from tests
