version: '3'

services:
  alice:
    image: hmans/crankypants:${CIRCLE_BRANCH:-master}
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      - CRANKY_LOGIN=alice
      - CRANKY_PASSWORD=secret
      - CRANKY_TITLE=Hi, I'm Alice

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium

  tests:
    build: .
    volumes:
      - .:/code:cached
    depends_on:
      - alice
      - selenium
    command: bundle exec rspec
